### ISSUE TITLE
License

### ISSUE THREAD

**Issue by larshesel** [johnhamelink/elibphonenumber#1]
Hi there, what's the license of elibphonenumber?

**Comment by johnhamelink** [comment]
Hi @larshesel I've just added the MIT license to this lib - thanks for pointing out that it was missing.

**Comment by larshesel** [comment]
@artefactop can you give your blessing to this? this was originally your code, so I suppose we need to clear this with you. It would be fantastic if this is OK with you.

**Comment by artefactop** [comment]
Hi, I prefer Apache License 2.0 I will add it to my project in short term

**Comment by johnhamelink** [comment]
Ok guys, thanks for your input @artifactop I will move from MIT to Apache 2 to keep everything in line with upstream.

**Comment by johnhamelink** [comment]
License is now Apache 2.0.
