### ISSUE TITLE
Hex

### ISSUE THREAD

**Issue by silviucpp** [johnhamelink/elibphonenumber#14]
Hello,

I tried to publish today the package but I saw you did it first :))
Idea is that in last time I did lot of changes and also merged bug fixing sent by others to the library and users using Hex won't be able to have access to this if you don;t merge all the time my changes

Thanks,
Silviu

**Comment by johnhamelink** [comment]
Hi there :)

Happy to give you the reigns as I’m not maintaining my fork anymore.

I’m in the middle of a house move, but I’ll get in touch with you in the next day or two.

**Comment by silviucpp** [comment]
Ok thanks. I'm maintaining my repo because I'm using it in several active projects.

**Comment by silviucpp** [comment]
Hello @johnhamelink  any news on this ?

**Comment by johnhamelink** [comment]
@silviucpp I'm sorry it's taken me so long to get back to you on this... I've added you as a collaborator to this project so you can control it :)

**Comment by silviucpp** [comment]
Hello,

I don't think that making me colaborator on your fork is what we need. I think you need to reassign the ownership of the package to me. 

To reassign ownership of a package to a different user or to another username, you can use the hex.owner task. My hex user is silviu.cpp

**Comment by johnhamelink** [comment]
@silviucpp this has been done now :) thanks for your patience on this!
